
spring:
  application:
    name: estilopropio
  resources:
    add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
  cache:
    caffeine:
      spec: maximumSize=10000, expireAfterWrite=60
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      sql: debug
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: jdbc:mysql://localhost:3306/estilopropio
    username: root
    password: 1061734652
    driverClassName: com.mysql.cj.jdbc.Driver
    auto-commit: true
    initialization-mode: always

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: loggers
  endpoint:
    loggers:
      enabled: true

server:
  compression:
    enabled: true # Whether response compression is enabled.
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json # Comma-separated list of MIME types that should be compressed.
    min-response-size: 1024 # Minimum "Content-Length" value that is required for compression to be performed.
  port: 8080


